# Generated by Django 4.0.4 on 2022-05-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('ST', 'Short Term'), ('LT', 'Long Term')], default='ST', max_length=50)),
                ('has_project_list', models.BooleanField(default=False)),
                ('has_course_list', models.BooleanField(default=False)),
                ('has_deadline', models.BooleanField(default=False)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=3000, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
